name: Build image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag redis:latest
    - name: Container registry login
      run: echo "${{ secrets.GL_TOKEN }}"| docker login -u "${{ secrets.GL_TOKEN_NAME }}" --password-stdin registry.gitlab.com
    - name: Image tag
      run: docker tag redis:latest registry.gitlab.com/radeld/toolbox/redis:latest
    - name: Image push
      run: docker push registry.gitlab.com/radeld/toolbox/redis:latest
